<?php
echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "<head>\n";
echo "	<title>　　　　　　　　　　王老帅与荔枝ofMCserver官网（试运行）　　　　　　　　　　　　　　　　　　　　　　　　　　　</title>\n";
echo "	<style>\n";
echo "		body background=\"image.jpg\"\n";
echo "		\n";
echo "		}\n";
echo "		nav {\n";
echo "			background-color: #eee;\n";
echo "			padding: 10px;\n";
echo "		}\n";
echo "		nav ul {\n";
echo "			margin: 0;\n";
echo "			padding: 0;\n";
echo "			list-style: none;\n";
echo "			text-align: center;\n";
echo "		}\n";
echo "		nav li {\n";
echo "			display: inline-block;\n";
echo "			margin: 0 10px;\n";
echo "		}\n";
echo "		nav a {\n";
echo "			color: #333;\n";
echo "			text-decoration: none;\n";
echo "			font-size: 18px;\n";
echo "		}\n";
echo "		section {\n";
echo "			margin: 20px;\n";
echo "			padding: 20px;\n";
echo "			border: 1px solid #ccc;\n";
echo "		}\n";
echo "	</style>\n";
echo "</head>\n";
echo "<body>\n";
echo "	<header>\n";
echo "		<h1>王老帅与荔枝ofMCserver官网（试运行）</h1>\n";
echo "	</header>\n";
echo "<img src=\"image.jpg\"  little=\"加了光影的服务器照片最终效果实际光影有你加的光影有关\" alt=\"图片被ban了>\n";
echo "</body>\n";
echo "	<nav>\n";
echo "		<ul>\n";
echo "			<li>首页</li>\n";
echo "			<li>关于server（没写）</li>\n";
echo "			<li>服务器简介（没写）</li>\n";
echo "			<li>服务器条例（去群里看看）</li>\n";
echo "                                      <li>请注意，服务器如果遭遇非法攻击，我们将停止数天躲避攻击，直到服务器没有受到攻击时方可正常访问</li>\n";
echo "		</ul>\n";
echo "	</nav>\n";
echo "	<section id=\"home\">\n";
echo "		<h2>欢迎来到我们的官网</h2>\n";
echo "		<p>我们的服务器是关于养老的，欢乐的，机械化的服务器   官网注意：请注意，服务器如果遭遇非法攻击，我们将停止数天躲避攻击，直到服务器没有受到攻击时方可正常访问（此网站也是一样和服务器同理）.</p >\n";
echo "	</section>\n";
echo "	<section id=\"about\">\n";
echo "		<h2>我为什么要开好一个服务器？</h2>\n";
echo "		<p>1.我个人与我朋友联机太麻烦了，本地电脑要开，于是我想开个服务器并邀请了我兄弟当副腐竹</p >\n";
echo "	</section>\n";
echo "	<section id=\"services\">\n";
echo "		<h2>服务器简短的规则</h2>\n";
echo "		<p>1.不要开挂、不要作弊、平等的对待任何人.</p >\n";
echo "	</section>\n";
echo "	<section id=\"contact\">\n";
echo "		<h2>联系我们</h2>\n";
echo "		<p>畅玩服务器联系我们wanglaoshuai720820@163.com，或者申诉的请联系wanglaoshuai720820@163.com.加入官方QQ群906958572掌握更多信息。</p >\n";
echo "	</section>\n";
echo "<div>Copyright &copy;2024 <a target=\"_red\" style=\"color:#FF\">王老帅与荔枝ofMCserver保留一切权力</a>. All Rights Reserved</div>\n";
echo "			</div>\n";
echo "</body>\n";
echo "</html>\n";
?>